fix!: validate not article markdown

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -54,20 +54,6 @@ jobs:
           dry-run: true
           github-token: ${{ secrets.GITHUB_TOKEN }}
 
-  use: # make sure the action works on a clean machine without building
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v4
-        with:
-          fetch-depth: 2 # Because if `fetch-depth >= 2` is not set, unchanged files will be updated.
-      - run: "git log -m -1 --name-only --pretty=format: HEAD"
-      - run: "git log -m -1 --name-only HEAD"
-      - uses: ./
-        with:
-          published: true
-          force-push: true
-          github-token: ${{ secrets.GITHUB_TOKEN }}
-
   use-with-validate-only:
     runs-on: ubuntu-latest
     steps:
@@ -77,15 +63,22 @@ jobs:
       - run: "git log -m -1 --name-only --pretty=format: HEAD"
       - run: "git log -m -1 --name-only HEAD"
       - run: |
-          cp ./src/__tests__/sampleMarkdown.md .
+          cp ./src/__tests__/invalidMarkdown.md .
           git config --global user.email "github-actions[bot]@users.noreply.github.com"
           git config --global user.name "github-actions[bot]"
           git add -A
           git commit -m "test"
       - name: "Execute validate-only. This step must fail. Print 'Error: Invalid metadata: emoji'."
         uses: ./
+        id: action
         with:
           validate-only: true
           commit-sha: .
           github-token: ${{ secrets.GITHUB_TOKEN }}
         continue-on-error: true
+      - if: ${{ steps.action.outcome == 'failure' }}
+        run: echo "Success"
+      - if: ${{ steps.action.outcome == 'success' }}
+        run: |
+          echo "Failure"
+          exit 1
